FROM elasticsearch:5.0

MAINTAINER Jonathan Martin <jonathan@yuzu.co>

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-file && \
	/usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack