#!/bin/sh
exec 2>&1

# Change the ownership of /usr/share/elasticsearch/data to elasticsearch
chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data

exec chpst -u elasticsearch /usr/share/elasticsearch/bin/elasticsearch $ES_OPTIONS
